// src/pages/Index.tsx
import React from 'react';

const Index: React.FC = () => {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100">
      <div className="text-center">
        <h1 className="text-4xl font-bold mb-4">Welcome to Your Blank App</h1>
        <p className="text-xl text-gray-600">Start building your amazing project here!</p>
      </div>
    </div>
  );
};

export default Index;

// src/pages/Index.svelte
<script lang="ts">
  // You can add any necessary imports here
</script>

<div class="min-h-screen flex items-center justify-center bg-gray-100">
  <div class="text-center">
    <h1 class="text-4xl font-bold mb-4">Welcome to Your Svelte App</h1>
    <p class="text-xl text-gray-600">Start building your amazing project here!</p>
  </div>
</div>
