// src/App.tsx
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { navItems } from "./nav-items";

const queryClient = new QueryClient();

const App: React.FC = () => (
  <QueryClientProvider client={queryClient}>
    <TooltipProvider>
      <Toaster />
      <BrowserRouter>
        <Routes>
          {navItems.map(({ to, page }) => (
            <Route key={to} path={to} element={page} />
          ))}
        </Routes>
      </BrowserRouter>
    </TooltipProvider>
  </QueryClientProvider>
);

export default App;

// src/App.svelte
<script>
  import { Router, Route } from "svelte-routing";
  import { Toaster } from "@/components/ui/sonner";
  import { TooltipProvider } from "@/components/ui/tooltip";
  import { QueryClient, QueryClientProvider } from "@tanstack/svelte-query";
  import { navItems } from "./nav-items";

  const queryClient = new QueryClient();
</script>

<QueryClientProvider client={queryClient}>
  <TooltipProvider>
    <Toaster />
    <Router>
      {#each navItems as { to, component }}
        <Route path={to} component={component} />
      {/each}
    </Router>
  </TooltipProvider>
</QueryClientProvider>
